version: '3'
services:
  web:
    working_dir: /of-the-new-day
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./:/of-the-new-day"
    command: bash -c "bin/rails s -b '0.0.0.0' -p 3000"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - postgres
    environment:
      RAILS_ENV: 'development'
    links:
      - postgres:postgres

  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - $HOME/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'

  redis:
    image: redis:7.2-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/data'

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

